# pytorch基础

### （1）numpy

In [22]:
import numpy as np

list1 = [1, 3, 2]

# 从已有数据类型list生成。list中的数据指的是ndarray的维度大小。
nd1 = np.ndarray(list1)
print("nd1:\n", "type: ", type(nd1))
print("value:\n", nd1)

list2 = [[2, 4, 1, 4], [4, 3, 2, 1]]
nd2 = np.array(list2)  # 嵌套数据可以转换为多维ndarray。
print("\n")
print("nd2:\n", "type: ", type(nd2))
print("value:\n", nd2)

nd1:
 type:  <class 'numpy.ndarray'>
value:
 [[[4.22793572e-307 1.69122046e-306]
  [1.05700260e-307 1.44635488e-307]
  [3.33773471e-307 4.22793572e-307]]]


nd2:
 type:  <class 'numpy.ndarray'>
value:
 [[2 4 1 4]
 [4 3 2 1]]


In [26]:
# numpy.random的使用

import numpy as np

# np.random.seed(1)  # 设置随机数种子，使每次生成的随机数一样。
rand1 = np.random.random([2, 2])  # 生成0到1之间的随机数。
rand2 = np.random.uniform(0, 10, [2, 2])  # 生成均匀分布的随机数。
rand3 = np.random.randn(2, 2)  # 标准正态的随机数
np.random.shuffle(rand3)  # 随机原地打乱顺序

print("rand1:\n", rand1)
print("rand2:\n", rand2)
print("rand3:\n", rand3)

rand1:
 [[0.54159249 0.5121131 ]
 [0.77661695 0.67546711]]
rand2:
 [[6.57377192 8.18141366]
 [9.87104655 6.30292479]]
rand3:
 [[ 0.17964116  0.12945487]
 [-3.05509823 -0.73564728]]


In [30]:
# 创建特定形状的多维数组
import numpy as np

np1 = np.zeros(shape=(2, 3), dtype=np.uint8)  # 大小为2x2的元素全为0的数组
np2 = np.ones(shape=(2, 3), dtype=np.uint8)  # 大小为2x2的元素全为1的数组

# 大小为2x2，左上到右下对角线元素为1，其余元素为0的矩阵.
np3 = np.eye(2, dtype=np.uint8)
np4 = np.empty(shape=(2, 3))  # 大小为2x2的空数组，其数据的值是未初始化的垃圾值。
np5 = np.full((2, 3), 6)  # 大小为2x3，且全部元素都为6的数组。

# 利用arange、linspace函数生成数组
ar1 = np.arange(10, 0, -1)  # 参数依次为初始值、终止值、步长（默认为1）
lin1 = np.linspace(0, 1, 5)  # 将初始值到终止值分为参数num份，

print("np1:\n", np1), print("np2:\n", np2)
print("np3:\n", np3), print("np4:\n", np4)
print("np5:\n", np5), print("ar1:\n", ar1),
print("lin1:\n", lin1)

np1:
 [[0 0 0]
 [0 0 0]]
np2:
 [[1 1 1]
 [1 1 1]]
np3:
 [[1 0]
 [0 1]]
np4:
 [[4.22793572e-307 1.69122046e-306 1.05700260e-307]
 [1.44635488e-307 3.33773471e-307 4.22793572e-307]]
np5:
 [[6 6 6]
 [6 6 6]]
ar1:
 [10  9  8  7  6  5  4  3  2  1]
lin1:
 [0.   0.25 0.5  0.75 1.  ]


In [31]:
# numpy的算数运算
import numpy as np

# 逐元素相乘，函数np.multiply(),或*。
np1 = np.ones((2, 2), dtype=np.uint8) * 3
np2 = np.ones((2, 2), dtype=np.uint8) * 2
multi1 = np.multiply(np1, np2)  # 相乘
multi2 = np1 * np2  # 相乘
multi3 = np1 * 2  # 直接和标量相乘，每个元素位置都乘以标量。

# 点积运算，遵循矩阵乘法
# numpy.dot(a, b, out=None)
a = np.array([[2, 3], [2, 2]])
b = np.array([[2, 3, 4], [2, 2, 4]])
dot = np.dot(a, b)

print("multi2:\n", multi2)
print("dot:\n", dot)

multi2:
 [[6 6]
 [6 6]]
dot:
 [[10 12 20]
 [ 8 10 16]]


In [34]:
# 数组变形。包括展平、连接等。
import numpy as np

# reshape更改维度，不修改向量本身。
arr1 = np.random.randint(0, 10, size=(2, 2))  # 2x2数组
arr1.reshape(1, 4)  # reshape函数将向量维度更改为1行4列，但是arr1仍然是2x2大小。

# resize更改维度，且修改向量本身。
arr2 = np.random.randint(0, 10, size=(1, 2))

# resize函数将维度改为2行1列，且重新赋值给arr2，相当于arr2=arr2.resize()。
arr2.resize(2, 1)
arr3 = (np.array([[1, 2, 3]])).T  # 转置

# 展平操作，包括ravel和flatten，ravel不会产生原数组的副本，flatten返回原数组的副本。
re = np.array([[1, 2], [3, 4]])
reval = re.ravel()  # 值为[1,2,3,4]
flat = np.array([[3, 2], [2, 4]])
flatten = flat.flatten()  # 值为[3,2,2,4]

# squeeze把矩阵中大小为1的维度去掉，unsqueeze则是在指定位置增加大小为1的维度。
sq = np.ones((3, 2, 1))
# print(sq.squeeze()) #去掉大小为1的维度
# print(sq.squeeze().shape) #结果为（3,2）

# transpose，对高维矩阵进行轴对换，比如把图片中表示颜色顺序的RGB改为GBR。
trans = np.arange(24).reshape(2, 3, 4)
# print(trans.shape)  # (2, 3, 4)
# print(trans.transpose(1, 2, 0).shape)  # 调换0，1,2通道的顺序，结果是(3, 4, 2)

# 合并数组。包括append、concatenate、stack、hstack、vstack、dstack、vsplit等。
app1 = np.arange(4).reshape(2, 2)
app2 = np.arange(4).reshape(2, 2)
lian_jie1 = np.append(app1, app2, axis=0)  # 按行合并，大小是4x2。
lian_jie2 = np.append(app1, app2, axis=1)  # 按列合并，大小是2x4。

app11 = np.array([[1, 2], [3, 4]])
app12 = np.array([[2, 3]])

# 对哪个维度使用concatenate，需要确保另一个维度的大小相等才能成功。
concatenate1 = np.concatenate((app11, app12), axis=0)  # 按行连接，大小是3x2。

# 按列连接，结果是[[1,2,2],[3,4,3]]
concatenate2 = np.concatenate((app11, app12.T), axis=1)
# stack是沿指定轴堆叠数组或矩阵。注意只是堆叠效果，并没有合并。
sta1 = np.array([[2, 3], [5, 4]])
sta2 = np.array([[7, 6], [9, 1]])
stack = np.stack((sta1, sta2), axis=0)

### （2）pytorch

#### 2.1 torch基础

In [ ]:
import torch

# torch.tensor和torch.Tensor区别：
# 1）torch.Tensor是torch.empty和torch.tensor之间的一种混合，
# 但是，当传入数据时，torch.Tensor使用全局默认dtype（FloatTensor），
# 而torch.tensor是从数据中推断数据类型。

# 2）torch.tensor(1)返回一个固定值1，
# 而torch.Tensor(1)返回一个大小为1的张量，它是随机初始化的值。

# 常用张量创建方法
t1 = torch.tensor(1)  # 结果是固定值1，t1类型是torch.LongTensor
t2 = torch.Tensor(1)  # 结果是大小为1的张量，t2类型是torch.FloatTensor
torch_eye = torch.eye(2, 2)  # 单位矩阵
torch_zero = torch.zeros(2, 3)  # 0矩阵
torch_one = torch.ones(3, 2)  # 1矩阵
linspace = torch.linspace(0, 10, 3)  # 0~10分三份，结果是0、5、10。
rand = torch.rand(2, 3)  # 均匀分布随机数
randn = torch.randn(3, 2)  # 标准分布随机数

# 修改张量形状
torch_size = torch.tensor([[1, 2], [3, 4]])
# print(torch_size.size())  # size和shape等价，返回结果都是torch.Size([2, 2])
# print(torch_size.shape)
# print(torch_size.view(4, 1))  # torch.view将其变为1x4矩阵。
# print(torch_size.view(-1))  # 参数为-1时表示展平数组。
# print(torch_size.unsqueeze(0))  # 增加一个维度
# print(torch_size.numel())  # 返回矩阵的元素数量。

# torch.view和torch.reshape()的区别：
# 1）reshape()可以由torch.reshape()，也可由torch.Tensor.reshape()调用。但view()只可由torch.Tensor.view()来调用。
# 2）对于一个将要被view的Tensor，新的size必须与原来的size与stride兼容。否则，在view之前必须调用contiguous()方法。
# 3）同样也是返回与input数据量相同，但形状不同的Tensor。若满足view的条件，则不会copy，若不满足，则会copy。
# 4）如果只想重塑张量，请使用torch.reshape。如果还关注内存使用情况并希望确保两个张量共享相同的数据，使用torch.view。

#### 2.2 python列表到pytorch张量

In [38]:
import torch

a = torch.ones(3)
s = torch.tensor([[1, 2], [4, 21], [2, 4]], dtype=torch.float32)
# print(s.shape) # torch.Size([3, 2])
some_list = list(range(6))
# print(some_list[:])
# print(some_list[0:4])  # 第0个元素到第三个元素，不包含第四个元素。
# print(some_list[1:])  # 第一个元素及之后的元素
# print(some_list[:4])  # 第四个元素之前的元素，不包含第四个元素。
# print(some_list[:-1])  # 最后一个元素之前的元素
# print(some_list[1:5:2])  # 第一个元素到第五个元素，步长2，不包含第五个元素。

In [43]:
batch = torch.randn(2, 3, 5, 5)
print(batch.mean(-3).shape)
# refine_names可以重新命名张量每个通道的名字，省略号表示靠前面的通道省略不更改。
batch_named = batch.refine_names(..., "batch", "channel", "row", "column")
print(batch_named)  # 返回的仍然是那个张量，只是通道名称改变了。

torch.Size([2, 5, 5])
tensor([[[[ 1.3317, -0.3455,  0.3835, -2.3680, -1.8817],
          [-0.0970, -0.4404, -1.0819,  0.0136,  0.0991],
          [ 0.1068, -0.3804,  0.6227, -1.1191, -0.5852],
          [ 1.4787, -1.4190, -0.7759,  1.0062,  0.0656],
          [-0.3153,  0.9107, -0.7760, -0.5247, -0.1659]],

         [[-0.0888, -0.9776, -1.0956, -0.6463,  0.0157],
          [-1.6564, -1.2394,  0.8805, -0.9841,  0.6795],
          [-1.6836, -0.9358,  0.2225,  0.9888, -2.2063],
          [ 0.0315, -0.5758,  0.9893,  1.8348,  0.4028],
          [ 1.4988, -0.3120, -0.5384,  0.9154, -0.3219]],

         [[-1.2571,  1.1100,  0.4570,  0.2759, -0.3344],
          [-0.4061, -0.7592, -0.7412,  1.0445, -0.3408],
          [-0.4523, -1.0053,  0.4949, -1.5809, -0.3259],
          [-0.3657,  0.7741,  1.1448,  0.8759, -0.4817],
          [ 0.7621,  0.2310, -0.5415,  0.9914,  1.2362]]],


        [[[ 0.1369,  0.0939, -0.5127,  0.5519,  0.1398],
          [-0.2210,  0.9679,  2.5564, -0.7045, -1.3222],
 

In [44]:
# 指定数据类型的方法
double_tensor1 = torch.ones(2, 3, dtype=torch.double)  # double就是float64
double_tensor2 = torch.ones(2, 3).double()  # 点方法

# 使用to，底层会检查转换是否必要。
# 在操作中输入多种类型时，输入会自动向较大类型转换。
double_tensor3 = torch.ones(2, 3).to(torch.double)

In [47]:
# 转置

double_tensor1 = torch.ones(2, 3, dtype=torch.double)  # double就是float64
transpose1 = torch.transpose(double_tensor1, 0, 1)  # 转置函数
transpose2 = double_tensor1.transpose(0, 1)  # 转置方法

print(transpose1.storage())  # 访问张量的存储区，
# 尽管张量显示自己有3行2列，但底层的存储区是一个大小为6的连续数组。
# 从这个意义上说，张量只知道如何将一对索引转换成存储区中的一个位置。

# 如果改变存储区的值，原值就会跟着改变。
transpose1_storage = transpose1.storage()
transpose1_storage[0] = 2  # 将存储区的第一个数改变，原值就会改变。

print(transpose1)  # 第一个数已经改变。

 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float64, device=cpu) of size 6]
tensor([[2., 1.],
        [1., 1.],
        [1., 1.]], dtype=torch.float64)


In [51]:
# 原地修改，一般在方法的末尾加下划线表示。意思就是修改之后将值返回给原来的变量。
one = torch.ones(2, 2)
one.zero_()

print("one:\n", one)  # 已经变为0

# 步长是一个元组，指示当索引在每个维度中增加1时在存储区中必须跳过的元素数量。
print("one stride: ", one.stride())  # 结果是（2,1）

# 更改子张量同样会导致原张量更改，因为都是对同样的存储空间进行操作。
large_tensor = torch.tensor([[2, 3], [3, 4], [5, 4]])
small_tensor = large_tensor[0]  # 将第0行,即[2,3]作为子张量
small_tensor[0] = 11  # 修改子张量的第0个数，即将0改为11。
print(large_tensor)  # 原张量变为[[11,3],[3,4],[5,4]]

one:
 tensor([[0., 0.],
        [0., 0.]])
one stride:  (2, 1)
tensor([[11,  3],
        [ 3,  4],
        [ 5,  4]])


In [57]:
# 转置，转置之后也是和原张量使用同样底层存储空间。不分配新内存，只创建新的tensor实例。

tensor = torch.tensor([[3, 2], [5, 7], [4, 9]])
t_tensor = tensor.t()  # 转置方法.t()
print(t_tensor)  # [[3,5,4],[2,7,9]]

# 验证是否共享存储区，返回True。
print("转置后是否共享存储空间： ", id(tensor.storage()) == id(t_tensor.storage()))
print("转置前后步长对比： ", tensor.stride(), t_tensor.stride())  # 步长对比

tensor([[3, 5, 4],
        [2, 7, 9]])
转置后是否共享存储空间：  True
转置前后步长对比：  (2, 1) (1, 2)


In [59]:
# 任意维度的转置
some_tensor = torch.ones(2, 3, 5)
t_some_tensor = some_tensor.transpose(0, 2)  # 交换第0维和第2维
print(t_some_tensor.shape)  # 形状变为torch.Size([5, 3, 2])

# 转置之后存储空间不连续。
print(some_tensor.is_contiguous(), t_some_tensor.is_contiguous())

torch.Size([5, 3, 2])
True False


In [60]:
# 使用contiguous()方法将转置之后的张量存储空间变为连续。
points = torch.tensor([[2.0, 3.0], [5.0, 7.0], [4.0, 9.0]])
t_points = points.t()

# 转置后是[[2., 5., 4.],[3., 7., 9.]]，
# 但存储顺序是按照列排列的2,3,5,7,4,9，不是行排列。
print(t_points.storage())
contiguous_points = t_points.contiguous()  # 转换为连续存储空间

# 连续存储空间是按照行排列，结果是2., 5., 4.,3., 7., 9.
print(contiguous_points.storage())

 2.0
 3.0
 5.0
 7.0
 4.0
 9.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]
 2.0
 5.0
 4.0
 3.0
 7.0
 9.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]


In [62]:
# 张量存储到GPU，加速运算。
gpu_tensor = torch.tensor(
    [[2, 3], [5, 4]], device="cuda:0" if torch.cuda.is_available() else "cpu"
)

# 直接将创建的张量复制到gpu。
gpu_tensor1 = gpu_tensor.to(device="cuda:0")

# 运算是在gpu上执行，gpu分配一个新的张量存储该结果的句柄，没有信息流到cpu。
gpu_tensor2 = gpu_tensor + 3

# 使用.to()方法将张量转移到cpu。
gpu_tensor2 = gpu_tensor2.to(device="cpu")

# 使用简写的.cuda()或.cpu()也可转移张量
gpu_tensor3 = gpu_tensor2.cuda(0)  # 默认索引也是0
gpu_tensor4 = gpu_tensor3.cpu()

In [64]:
# tensor和numpy之间的转换
ten = torch.ones(2, 3)  # 在cpu上的张量

# 转换为numpy类型，和张量存储共享相同的底层缓冲区，
ten_np = ten.numpy()
ten_np[0, 0] = 22  # 修改numpy类型，张量也会改变。

# 将numpy类型转换为torch。# tensor和numpy之间的转换
pytorch_tensor = torch.from_numpy(ten_np)
ten = torch.ones(2, 3)  # 在cpu上的张量
ten_np = ten.numpy()  # 转换为numpy类型，和张量存储共享相同的底层缓冲区，
ten_np[0, 0] = 22  # 修改numpy类型，张量也会改变。
pytorch_tensor = torch.from_numpy(ten_np)  # 将numpy类型转换为torch。

#### 2.3 Dataset和DataLoader的使用

In [70]:
# Dataset定义__len__和__getitem__方法，分别获取数据长度和每一份数据的信息，
# DataLoader则成批次加载数据，
# 传入的参数包括数据集Dataset、批次大小batch_size、是否打乱数据shuffle。

import torch.nn as nn
from torch.utils.data import DataLoader, Dataset
import torch

# 简单的测试数据
x = [[1, 2], [3, 4], [5, 6], [7, 8]]
y = [[3], [7], [11], [15]]
device = "cuda:0" if torch.cuda.is_available() else "cpu"
X = torch.tensor(x).float()
Y = torch.tensor(y).float()
X = X.to(device)
Y = Y.to(device)


# 创建自己的数据集类my_dataloader,继承自Dataset，重写__len__()和__getitem__()。
class my_dataloader(Dataset):
    def __init__(self, x, y):
        self.x = torch.tensor(x).float()
        self.y = torch.tensor(y).float()

    def __len__(self):
        return len(self.x)

    def __getitem__(self, ix):
        return self.x[ix], self.y[ix]


my_data = my_dataloader(X, Y)  # 获取所有的数据
data_loader = DataLoader(my_data, batch_size=1, shuffle=False)

print("测试数据为：\n")
for x, y in data_loader:
    print(x, y)


class my_net(nn.Module):
    def __init__(self):
        super().__init__()
        self.hidden_linear = nn.Linear(in_features=2, out_features=8)
        self.hidden_active = nn.ReLU()
        self.output_linear = nn.Linear(in_features=8, out_features=1)

    def forward(self, x):
        x = self.hidden_active(self.hidden_linear(x))
        x = self.output_linear(x)
        return x


# my_net = nn.Sequential(nn.Linear(2, 8), nn.ReLU(), nn.Linear(8, 1))
net = my_net()
net = net.to(device)


def my_mean_squared_loss(_y, y):
    loss = (_y - y) ** 2
    loss = loss.mean()
    return loss


loss_func = nn.MSELoss()
loss_val = loss_func(net(X), Y)
print("损失值为：\n", loss_val)

测试数据为：

tensor([[1., 2.]], device='cuda:0') tensor([[3.]], device='cuda:0')
tensor([[3., 4.]], device='cuda:0') tensor([[7.]], device='cuda:0')
tensor([[5., 6.]], device='cuda:0') tensor([[11.]], device='cuda:0')
tensor([[7., 8.]], device='cuda:0') tensor([[15.]], device='cuda:0')
损失值为：
 tensor(123.2943, device='cuda:0', grad_fn=<MseLossBackward0>)


C:\Users\世兰丁\AppData\Local\Temp\ipykernel_19156\2661343386.py:22: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  self.x = torch.tensor(x).float()
C:\Users\世兰丁\AppData\Local\Temp\ipykernel_19156\2661343386.py:23: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  self.y = torch.tensor(y).float()


#### 2.4 自动梯度autograd

autograd。pytorch自动求梯度的方法，其基于计算图（一种有向无环图）

如表达式z=wx+b,可以写成两个表达式：y=wx和z=y+b。x、w、b为变量，是用户创建的不依赖于其它变量的变量，故又称为叶子节点。
为计算各叶子节点的梯度，需要把对应的张量参数requires_grad属性设置为True，这样就可自动跟踪其历史记录。
y、z是计算得到的变量，非叶子节点，z为根节点。
其中的乘法和加法是算子，由这些变量和算子就构成一个完整的计算过程（或向前传播过程）。

pytorch调用backward()方法，会计算各节点的梯度，这是一个反向传播过程。

In [71]:
# （1）标量的反向传播

# 假设x、w、b都是标量，z=wx+b，对标量z调用backward()方法，无须对backward()传入参数。
import torch

x = torch.Tensor([2])  # requires_grad默认为False
w = torch.randn(1, requires_grad=True)
b = torch.randn(1, requires_grad=True)

y = torch.multiply(w, x)
z = torch.add(y, b)
# print(x.requires_grad, w.requires_grad, b.requires_grad)  # 结果为False True True
# print(y.requires_grad, z.requires_grad)  # 因为和w，b有依赖关系，所以y，z的requires_grad均为True。

# 查看各节点是否为叶子结点。w、x、b是叶子节点，y、z不是，z是根节点。
# print(w.is_leaf, x.is_leaf, b.is_leaf, y.is_leaf, z.is_leaf)  # True True True False False

# 查看叶子节点的grad_fn属性，w、x、b的grad_fn为None，
# y、z的grad_fn为<MulBackward0 object at 0x000001F70E182D70> <AddBackward0 object at 0x000001F70E182DA0>
# print(w.grad_fn, x.grad_fn, b.grad_fn, y.grad_fn, z.grad_fn)

# 基于z张量进行梯度反向传播,执行backward之后计算图会自动清空，
z.backward()
# 如果需要多次使用backward，需要修改参数retain_graph为True，此时梯度是累加的
# z.backward(retain_graph=True)
# 查看叶子节点的梯度，x是叶子节点但它无须求导，故其梯度为None
print("参数w、b、x的梯度分别为:{},{},{}".format(w.grad, b.grad, x.grad))

# 参数w、b、x的梯度分别为:tensor([2.]),tensor([1.]),None
# 非叶子节点的梯度，执行backward之后，会自动清空
print("非叶子节点y,z的梯度分别为:{},{}".format(y.grad, z.grad))
# 非叶子节点y,z的梯度分别为:None,None

参数w、b、x的梯度分别为:tensor([2.]),tensor([1.]),None
非叶子节点y,z的梯度分别为:None,None


C:\Users\世兰丁\AppData\Local\Temp\ipykernel_19156\351135770.py:31: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at C:\cb\pytorch_1000000000000\work\build\aten\src\ATen/core/TensorBody.h:494.)
  print("非叶子节点y,z的梯度分别为:{},{}".format(y.grad, z.grad))


（2）非标量的反向传播

目标张量一般都是标量，比如损失值loss。
标量使用backward()方法无须传参，那非标量如何反向传播呢？

PyTorch不让张量对张量求导，只允许标量对张量求导，
因此，如果目标张量对一个非标量调用backward()，则需要传入一个gradient参数，
该参数也是张量，而且需要与调用backward()的张量形状相同。
传入这个参数就是为了把张量对张量的求导转换为标量对张量的求导。

举一个例子来说，假设目标值为loss=(y1,y2,…,ym)，传入的参数为v=(v1,v2,…,vm)，
那么就可把对loss的求导，转换为对loss*(v.T)（v.T表示v的转置）标量的求导。
即将原来loss对x求偏导得到的雅可比矩阵乘以张量v.T（v的转置），便可得到需要的梯度矩阵。

In [74]:
import torch

# 定义叶子节点张量x，形状为1x2
x = torch.tensor([[2, 3]], dtype=torch.float, requires_grad=True)
J = torch.zeros(2, 2)  # 初始化Jacobian矩阵
y = torch.zeros(1, 2)  # 初始化目标张量，形状为1x2

# 定义y与x之间的映射关系：y1=x1**2+3*x2，y2=2*x1+x2**2
y[0, 0] = x[0, 0] ** 2 + 3 * x[0, 1]
y[0, 1] = x[0, 1] ** 2 + 2 * x[0, 0]

# y对x的梯度是一个雅可比矩阵，即[[2*x1,3],[2,2*x2]]。
# 当x1=2,x2=3时，雅可比矩阵为[[4,3],[2,6]],其转置就为[[4,2],[3,6]]

# 此时调用backward()获取y对x的梯度
# y.backward(torch.Tensor([[1, 1]]))
# print(x.grad)  # 结果为tensor([[6., 9.]])，这个结果和手工计算的结果不一致。

# 错误的原因是v的取值，这样得到的并不是y对x的梯度，这里我们可以分成两步计算：
# 首先让v=(1,0)得到y1对x的梯度，然后使v=(0,1)，得到y2对x的梯度。
# 这里因需要重复使用backward()，需要使参数retain_graph=True，

# 生成y1对x的梯度
y.backward(torch.Tensor([[1, 0]]), retain_graph=True)
J[0] = x.grad
# 梯度是累加的，故需要对x的梯度清零。
x.grad = torch.zeros_like(x.grad)

# 生成y2对x的梯度
y.backward(torch.Tensor([[0, 1]]))
J[1] = x.grad

# 显示jacobian矩阵的值
print(J)

tensor([[4., 3.],
        [2., 6.]])


### （3）神经网络工具箱torch.nn

构建网络层可以基于Module类或函数（nn.functional）。
nn中的大多数层在functional中都有与之对应的函数。

主要区别是nn.Module可自动提取可学习的参数，
一般用在卷积层、全连接层、Dropout层等含有可学习参数的层。
nn.functional则像是纯函数，一般用在激活函数、池化等无可学习参数的层。

In [ ]:
# 此处代码无法直接运行。需要下载好MNIST数据集，并修改训练、测试数据的路径。

# 手写数字识别程序代码：
"""
import torch
import numpy as np
from torchvision.datasets import mnist  # 手写数字识别数据集
import torchvision.transforms as transforms  # 变换
from torch.utils.data import DataLoader  # 数据加载器
import torch.nn.functional as F  # 函数functional
import torch.optim as optim  # 优化器
from torch import nn  # 神经网络工具箱

# 定义超参数
train_batch_size = 64
test_batch_size = 128
learning_rate = 0.01
num_epoches = 20
momentum = 0.5
lr = 0.1

transform = transforms.Compose([
    transforms.ToTensor(),  # 转换为张量
    transforms.Normalize([0.5], [0.5])  # 归一化，参数分别为均值和方差
])
# 加载数据
train_dataset = mnist.MNIST('./data', train=True, transform=transform, download=False)
test_dataset = mnist.MNIST('./data', train=False, transform=transform)
train_loader = DataLoader(train_dataset, batch_size=train_batch_size, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=test_batch_size, shuffle=False)

import matplotlib.pyplot as plt  # 绘图工具

# 源数据示例
examples = enumerate(test_loader)  # 利用迭代器加载测试集的图片
batch_idx, (example_data, example_targets) = next(examples)
fig = plt.figure()

for i in range(6):
    plt.subplot(2, 3, i + 1)
    plt.tight_layout() # 布局紧致，使子图填满整张图。
    plt.imshow(example_data[i][0], cmap='gray', interpolation='none')
    plt.title("Ground Truth: {}".format(example_targets[i]))
    plt.xticks([])
    plt.yticks([])
plt.show()

# 定义神经网络类
class Net(nn.Module):
    def __init__(self, in_dim, n_hidden_1, n_hidden_2, out_dim):
        super(Net, self).__init__()
        self.layer1 = nn.Sequential(nn.Linear(in_dim, n_hidden_1), nn.BatchNorm1d(n_hidden_1))
        self.layer2 = nn.Sequential(nn.Linear(n_hidden_1, n_hidden_2), nn.BatchNorm1d(n_hidden_2))
        self.layer3 = nn.Sequential(nn.Linear(n_hidden_2, out_dim))

    def forward(self, x):  # 前向传播
        x = F.relu(self.layer1(x))
        x = F.relu(self.layer2(x))
        x = self.layer3(x)
        return x


device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")  # 有GPU用GPU
model = Net(28 * 28, 300, 100, 10)  # 实例化网络
model.to(device)  # 模型移动到使用的设备上，此电脑是GPU。
criterion = nn.CrossEntropyLoss()  # 损失函数
optimizer = optim.SGD(model.parameters(), momentum=momentum)  # 优化器

# 存储训练、测试数据的列表
losses = []
acces = []
eval_losses = []
eval_acces = []

for epoch in range(num_epoches):  # 训练
    train_loss = 0
    train_acc = 0
    model.train()  # 切换到训练模式
    
    if epoch % 5 == 0:  # 每训练5轮学习率降为原来的0.1。
        optimizer.param_groups[0]['lr'] *= lr
        
    for img, label in train_loader:
        img = img.to(device)
        label = label.to(device)
        img = img.view(img.size(0), -1)
        out = model(img)
        loss = criterion(out, label)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        train_loss += loss.item()
        _, pred = out.max(1)
        num_correct = (pred == label).sum().item()
        acc = num_correct / img.shape[0]
        train_acc += acc
        
    losses.append(train_loss / len(train_loader))
    acces.append(train_acc / len(train_loader))
    eval_loss = 0
    eval_acc = 0
    model.eval()
    
    for img, label in test_loader:
        img = img.to(device)
        label = label.to(device)
        img = img.view(img.size(0), -1)
        out = model(img)
        loss = criterion(out, label)
        eval_loss += loss.item()
        _, pred = out.max(1)
        num_correct = (pred == label).sum().item()
        acc = num_correct / img.shape[0]
        eval_acc += acc
        
    eval_losses.append(eval_loss / len(test_loader))
    eval_acces.append(eval_acc / len(test_loader))
    print('epoch:{},train_loss:{},train_acc:{},test_loss:{},test_acc:{}'
          .format(epoch, train_loss / len(train_loader), train_acc / len(train_loader),
                  eval_loss / len(test_loader), eval_acc / len(test_loader)))

plt.title('trainloss')
plt.plot(np.arange(len(losses)), losses)
plt.legend(['Train Loss'], loc='upper right')
plt.show()
"""