# pytorch基础

### （1）numpy

In [22]:
import numpy as np

list1 = [1, 3, 2]

# 从已有数据类型list生成。list中的数据指的是ndarray的维度大小。
nd1 = np.ndarray(list1)
print("nd1:\n", "type: ", type(nd1))
print("value:\n", nd1)

list2 = [[2, 4, 1, 4], [4, 3, 2, 1]]
nd2 = np.array(list2)  # 嵌套数据可以转换为多维ndarray。
print("\n")
print("nd2:\n", "type: ", type(nd2))
print("value:\n", nd2)

nd1:
 type:  <class 'numpy.ndarray'>
value:
 [[[4.22793572e-307 1.69122046e-306]
  [1.05700260e-307 1.44635488e-307]
  [3.33773471e-307 4.22793572e-307]]]


nd2:
 type:  <class 'numpy.ndarray'>
value:
 [[2 4 1 4]
 [4 3 2 1]]


In [26]:
# numpy.random的使用

import numpy as np

# np.random.seed(1)  # 设置随机数种子，使每次生成的随机数一样。
rand1 = np.random.random([2, 2])  # 生成0到1之间的随机数。
rand2 = np.random.uniform(0, 10, [2, 2])  # 生成均匀分布的随机数。
rand3 = np.random.randn(2, 2)  # 标准正态的随机数
np.random.shuffle(rand3)  # 随机原地打乱顺序

print("rand1:\n", rand1)
print("rand2:\n", rand2)
print("rand3:\n", rand3)

rand1:
 [[0.54159249 0.5121131 ]
 [0.77661695 0.67546711]]
rand2:
 [[6.57377192 8.18141366]
 [9.87104655 6.30292479]]
rand3:
 [[ 0.17964116  0.12945487]
 [-3.05509823 -0.73564728]]


In [30]:
# 创建特定形状的多维数组
import numpy as np

np1 = np.zeros(shape=(2, 3), dtype=np.uint8)  # 大小为2x2的元素全为0的数组
np2 = np.ones(shape=(2, 3), dtype=np.uint8)  # 大小为2x2的元素全为1的数组

# 大小为2x2，左上到右下对角线元素为1，其余元素为0的矩阵.
np3 = np.eye(2, dtype=np.uint8)
np4 = np.empty(shape=(2, 3))  # 大小为2x2的空数组，其数据的值是未初始化的垃圾值。
np5 = np.full((2, 3), 6)  # 大小为2x3，且全部元素都为6的数组。

# 利用arange、linspace函数生成数组
ar1 = np.arange(10, 0, -1)  # 参数依次为初始值、终止值、步长（默认为1）
lin1 = np.linspace(0, 1, 5)  # 将初始值到终止值分为参数num份，

print("np1:\n", np1), print("np2:\n", np2)
print("np3:\n", np3), print("np4:\n", np4)
print("np5:\n", np5), print("ar1:\n", ar1),
print("lin1:\n", lin1)

np1:
 [[0 0 0]
 [0 0 0]]
np2:
 [[1 1 1]
 [1 1 1]]
np3:
 [[1 0]
 [0 1]]
np4:
 [[4.22793572e-307 1.69122046e-306 1.05700260e-307]
 [1.44635488e-307 3.33773471e-307 4.22793572e-307]]
np5:
 [[6 6 6]
 [6 6 6]]
ar1:
 [10  9  8  7  6  5  4  3  2  1]
lin1:
 [0.   0.25 0.5  0.75 1.  ]


In [31]:
# numpy的算数运算
import numpy as np

# 逐元素相乘，函数np.multiply(),或*。
np1 = np.ones((2, 2), dtype=np.uint8) * 3
np2 = np.ones((2, 2), dtype=np.uint8) * 2
multi1 = np.multiply(np1, np2)  # 相乘
multi2 = np1 * np2  # 相乘
multi3 = np1 * 2  # 直接和标量相乘，每个元素位置都乘以标量。

# 点积运算，遵循矩阵乘法
# numpy.dot(a, b, out=None)
a = np.array([[2, 3], [2, 2]])
b = np.array([[2, 3, 4], [2, 2, 4]])
dot = np.dot(a, b)

print("multi2:\n", multi2)
print("dot:\n", dot)

multi2:
 [[6 6]
 [6 6]]
dot:
 [[10 12 20]
 [ 8 10 16]]


In [34]:
# 数组变形。包括展平、连接等。
import numpy as np

# reshape更改维度，不修改向量本身。
arr1 = np.random.randint(0, 10, size=(2, 2))  # 2x2数组
arr1.reshape(1, 4)  # reshape函数将向量维度更改为1行4列，但是arr1仍然是2x2大小。

# resize更改维度，且修改向量本身。
arr2 = np.random.randint(0, 10, size=(1, 2))

# resize函数将维度改为2行1列，且重新赋值给arr2，相当于arr2=arr2.resize()。
arr2.resize(2, 1)
arr3 = (np.array([[1, 2, 3]])).T  # 转置

# 展平操作，包括ravel和flatten，ravel不会产生原数组的副本，flatten返回原数组的副本。
re = np.array([[1, 2], [3, 4]])
reval = re.ravel()  # 值为[1,2,3,4]
flat = np.array([[3, 2], [2, 4]])
flatten = flat.flatten()  # 值为[3,2,2,4]

# squeeze把矩阵中大小为1的维度去掉，unsqueeze则是在指定位置增加大小为1的维度。
sq = np.ones((3, 2, 1))
# print(sq.squeeze()) #去掉大小为1的维度
# print(sq.squeeze().shape) #结果为（3,2）

# transpose，对高维矩阵进行轴对换，比如把图片中表示颜色顺序的RGB改为GBR。
trans = np.arange(24).reshape(2, 3, 4)
# print(trans.shape)  # (2, 3, 4)
# print(trans.transpose(1, 2, 0).shape)  # 调换0，1,2通道的顺序，结果是(3, 4, 2)

# 合并数组。包括append、concatenate、stack、hstack、vstack、dstack、vsplit等。
app1 = np.arange(4).reshape(2, 2)
app2 = np.arange(4).reshape(2, 2)
lian_jie1 = np.append(app1, app2, axis=0)  # 按行合并，大小是4x2。
lian_jie2 = np.append(app1, app2, axis=1)  # 按列合并，大小是2x4。

app11 = np.array([[1, 2], [3, 4]])
app12 = np.array([[2, 3]])

# 对哪个维度使用concatenate，需要确保另一个维度的大小相等才能成功。
concatenate1 = np.concatenate((app11, app12), axis=0)  # 按行连接，大小是3x2。

# 按列连接，结果是[[1,2,2],[3,4,3]]
concatenate2 = np.concatenate((app11, app12.T), axis=1)
# stack是沿指定轴堆叠数组或矩阵。注意只是堆叠效果，并没有合并。
sta1 = np.array([[2, 3], [5, 4]])
sta2 = np.array([[7, 6], [9, 1]])
stack = np.stack((sta1, sta2), axis=0)

### （2）pytorch

In [ ]:
import torch

# torch.tensor和torch.Tensor区别：
# 1）torch.Tensor是torch.empty和torch.tensor之间的一种混合，
# 但是，当传入数据时，torch.Tensor使用全局默认dtype（FloatTensor），
# 而torch.tensor是从数据中推断数据类型。

# 2）torch.tensor(1)返回一个固定值1，
# 而torch.Tensor(1)返回一个大小为1的张量，它是随机初始化的值。

# 常用张量创建方法
t1 = torch.tensor(1)  # 结果是固定值1，t1类型是torch.LongTensor
t2 = torch.Tensor(1)  # 结果是大小为1的张量，t2类型是torch.FloatTensor
torch_eye = torch.eye(2, 2)  # 单位矩阵
torch_zero = torch.zeros(2, 3)  # 0矩阵
torch_one = torch.ones(3, 2)  # 1矩阵
linspace = torch.linspace(0, 10, 3)  # 0~10分三份，结果是0、5、10。
rand = torch.rand(2, 3)  # 均匀分布随机数
randn = torch.randn(3, 2)  # 标准分布随机数

# 修改张量形状
torch_size = torch.tensor([[1, 2], [3, 4]])
# print(torch_size.size())  # size和shape等价，返回结果都是torch.Size([2, 2])
# print(torch_size.shape)
# print(torch_size.view(4, 1))  # torch.view将其变为1x4矩阵。
# print(torch_size.view(-1))  # 参数为-1时表示展平数组。
# print(torch_size.unsqueeze(0))  # 增加一个维度
# print(torch_size.numel())  # 返回矩阵的元素数量。

# torch.view和torch.reshape()的区别：
# 1）reshape()可以由torch.reshape()，也可由torch.Tensor.reshape()调用。但view()只可由torch.Tensor.view()来调用。
# 2）对于一个将要被view的Tensor，新的size必须与原来的size与stride兼容。否则，在view之前必须调用contiguous()方法。
# 3）同样也是返回与input数据量相同，但形状不同的Tensor。若满足view的条件，则不会copy，若不满足，则会copy。
# 4）如果只想重塑张量，请使用torch.reshape。如果还关注内存使用情况并希望确保两个张量共享相同的数据，使用torch.view。